"""added new columns to order and order details

Revision ID: 0b9d00a8930a
Revises: f3cfa90b960a
Create Date: 2024-09-30 20:15:32.465774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9d00a8930a'
down_revision = 'f3cfa90b960a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_rated', sa.Boolean(), nullable=False))

    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.drop_column('order_rating')

    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.drop_column('order_rated')

    # ### end Alembic commands ###
