"""added new colums to business

Revision ID: 0da0f4410b47
Revises: 96cad53db8bd
Create Date: 2024-09-11 15:41:16.824402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da0f4410b47'
down_revision = '96cad53db8bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('BusinessDetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account_number', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('bank_account_name', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('receipient_code', sa.String(length=30), nullable=True))

    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instant_pay', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.drop_column('instant_pay')

    with op.batch_alter_table('BusinessDetails', schema=None) as batch_op:
        batch_op.drop_column('receipient_code')
        batch_op.drop_column('bank_account_name')
        batch_op.drop_column('bank_account_number')

    # ### end Alembic commands ###
