"""added new columns to order table

Revision ID: 31b11e97f186
Revises: 5aa2a15ddfdc
Create Date: 2024-09-25 00:33:20.305659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31b11e97f186'
down_revision = '5aa2a15ddfdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_time_triggered', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('inspection_time_triggered', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.drop_column('inspection_time_triggered')
        batch_op.drop_column('delivery_time_triggered')

    # ### end Alembic commands ###
