"""added new columns to order table for elapsed times

Revision ID: 3efce2e036d7
Revises: a2797ea3e5df
Create Date: 2024-10-14 01:47:09.274123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3efce2e036d7'
down_revision = 'a2797ea3e5df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_time_elapsed', sa.Boolean()))
        batch_op.add_column(sa.Column('inspection_time_elapsed', sa.Boolean()))
        batch_op.add_column(sa.Column('dispute_time_triggered', sa.Boolean()))
        batch_op.add_column(sa.Column('dispute_time_elapsed', sa.Boolean()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.drop_column('dispute_time_elapsed')
        batch_op.drop_column('dispute_time_triggered')
        batch_op.drop_column('inspection_time_elapsed')
        batch_op.drop_column('delivery_time_elapsed')

    # ### end Alembic commands ###
