"""added a column to order

Revision ID: 47e1a5a09a3b
Revises: 650c21096a6e
Create Date: 2024-09-19 14:53:24.965008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e1a5a09a3b'
down_revision = '650c21096a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('BusinessDetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account_code', sa.String(length=10), nullable=True))

    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dispursement_processing', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.drop_column('dispursement_processing')

    with op.batch_alter_table('BusinessDetails', schema=None) as batch_op:
        batch_op.drop_column('bank_account_code')

    # ### end Alembic commands ###
