"""added metadata column to order details

Revision ID: 5aa2a15ddfdc
Revises: a793d5845c6b
Create Date: 2024-09-24 23:16:19.733173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa2a15ddfdc'
down_revision = 'a793d5845c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details_metadata', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.drop_column('details_metadata')

    # ### end Alembic commands ###
