"""added 2 new columns to customer

Revision ID: 650c21096a6e
Revises: 0da0f4410b47
Create Date: 2024-09-11 16:07:31.416876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650c21096a6e'
down_revision = '0da0f4410b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account_name', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('bank_account_number', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('bank_account_code', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customer', schema=None) as batch_op:
        batch_op.drop_column('bank_account_code')
        batch_op.drop_column('bank_account_number')
        batch_op.drop_column('bank_account_name')

    # ### end Alembic commands ###
