"""updated constraint back

Revision ID: 7a28020275c9
Revises: 3cf83d3b0ca4
Create Date: 2024-09-05 17:23:09.925300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a28020275c9'
down_revision = '3cf83d3b0ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_initiated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('order_commenced', sa.Boolean(), nullable=True))
        batch_op.alter_column('order_closed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.alter_column('order_closed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('order_commenced')
        batch_op.drop_column('order_initiated')

    # ### end Alembic commands ###
