"""added new column to product return

Revision ID: 7b1edbc2497f
Revises: f6b6f1e4d6d0
Create Date: 2024-10-19 22:39:56.189762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1edbc2497f'
down_revision = 'f6b6f1e4d6d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ProductReturn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_sent_out', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ProductReturn', schema=None) as batch_op:
        batch_op.drop_column('product_sent_out')

    # ### end Alembic commands ###
