"""removed constraint from customer table

Revision ID: 7cc5e02c2bfb
Revises: 4679399119ca
Create Date: 2024-10-02 15:46:23.325567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc5e02c2bfb'
down_revision = '4679399119ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customer', schema=None) as batch_op:
        batch_op.drop_constraint('Customer_email_address_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customer', schema=None) as batch_op:
        batch_op.create_unique_constraint('Customer_email_address_key', ['email_address'])

    # ### end Alembic commands ###
