"""added new_table

Revision ID: 7fad5aaddf72
Revises: faff9db1ed4c
Create Date: 2024-10-12 21:05:04.539593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fad5aaddf72'
down_revision = 'faff9db1ed4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProductReturn',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('buyer_initiates_return', sa.Boolean(), nullable=False),
    sa.Column('date_initiated_return', sa.DateTime(), nullable=True),
    sa.Column('product_in_transit', sa.Boolean(), nullable=False),
    sa.Column('buyer_confirm_return', sa.Boolean(), nullable=False),
    sa.Column('date_buyer_confirm_return', sa.DateTime(), nullable=True),
    sa.Column('seller_confirm_return', sa.Boolean(), nullable=False),
    sa.Column('date_seller_confirm_return', sa.DateTime(), nullable=True),
    sa.Column('returned_product_inspection_time_triggered', sa.Boolean(), nullable=False),
    sa.Column('returned_product_inspection_time', sa.Integer(), nullable=True),
    sa.Column('seller_accept_return_condition', sa.Boolean(), nullable=True),
    sa.Column('return_issue', sa.Text(), nullable=True),
    sa.Column('party_negotiation', sa.Boolean(), nullable=False),
    sa.Column('negotiation_result', sa.Text(), nullable=True),
    sa.Column('arbitration_needed', sa.Boolean(), nullable=False),
    sa.Column('arbitrator_used', sa.String(length=50), nullable=True),
    sa.Column('arbitrator_agreement_reached', sa.Boolean(), nullable=False),
    sa.Column('product_return_complete', sa.Boolean(), nullable=False),
    sa.Column('amount_to_refund', sa.Float(), nullable=False),
    sa.Column('date_of_completion', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['Order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ProductReturn', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ProductReturn_id'), ['id'], unique=False)

    with op.batch_alter_table('DeliveryInformation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_description', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DeliveryInformation', schema=None) as batch_op:
        batch_op.drop_column('delivery_description')

    with op.batch_alter_table('ProductReturn', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ProductReturn_id'))

    op.drop_table('ProductReturn')
    # ### end Alembic commands ###
