"""new columns on arbitration

Revision ID: 8c73edae106d
Revises: d5106eaeed10
Create Date: 2024-10-19 20:10:39.376823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c73edae106d'
down_revision = 'd5106eaeed10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Arbitration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_name', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('contract_data', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('mimetype', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Arbitration', schema=None) as batch_op:
        batch_op.drop_column('mimetype')
        batch_op.drop_column('contract_data')
        batch_op.drop_column('contract_name')

    # ### end Alembic commands ###
