"""new column on product return table - time for return

Revision ID: 8eb7d0a781bb
Revises: ba21d9040153
Create Date: 2024-10-18 00:34:29.178410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eb7d0a781bb'
down_revision = 'ba21d9040153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ProductReturn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_for_return', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ProductReturn', schema=None) as batch_op:
        batch_op.drop_column('time_for_return')

    # ### end Alembic commands ###
