"""added a column to order table

Revision ID: 9bbdf6f8f06c
Revises: c9640a35ab4f
Create Date: 2024-09-06 10:27:35.878964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bbdf6f8f06c'
down_revision = 'c9640a35ab4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_to_balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.drop_column('amount_to_balance')

    # ### end Alembic commands ###
