"""changed a constraint on the customer table

Revision ID: ab4a423578fe
Revises: 7c631d1ad385
Create Date: 2024-09-27 01:38:55.403521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab4a423578fe'
down_revision = '7c631d1ad385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TransactionCondition', schema=None) as batch_op:
        batch_op.alter_column('partial_disburse_requisite',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TransactionCondition', schema=None) as batch_op:
        batch_op.alter_column('partial_disburse_requisite',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
