"""new column on transaction condition - dispute_settled

Revision ID: ba21d9040153
Revises: 3efce2e036d7
Create Date: 2024-10-17 12:21:01.898556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba21d9040153'
down_revision = '3efce2e036d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TransactionCondition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dispute_settled', sa.Boolean()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TransactionCondition', schema=None) as batch_op:
        batch_op.drop_column('dispute_settled')

    # ### end Alembic commands ###
