"""upgraded constraint

Revision ID: c0951ef5ece2
Revises: 8c73edae106d
Create Date: 2024-10-19 20:31:32.634444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0951ef5ece2'
down_revision = '8c73edae106d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DeliveryInformation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('DeliveryInformation', schema=None) as batch_op:
        batch_op.drop_column('event')

    # ### end Alembic commands ###
