"""added constraints

Revision ID: c9640a35ab4f
Revises: 7a28020275c9
Create Date: 2024-09-05 17:27:47.305801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9640a35ab4f'
down_revision = '7a28020275c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.alter_column('order_initiated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('order_commenced',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('order_closed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.alter_column('order_closed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('order_commenced',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('order_initiated',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
