"""added abrittrate table and necessary columns to order table

Revision ID: d5106eaeed10
Revises: 8eb7d0a781bb
Create Date: 2024-10-19 19:23:19.793202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5106eaeed10'
down_revision = '8eb7d0a781bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Arbitration',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('independent_body_name', sa.String(length=30), nullable=False),
    sa.Column('ongoing', sa.Boolean(), nullable=False),
    sa.Column('initiation_date', sa.DateTime(), nullable=True),
    sa.Column('arbitrate_fees', sa.Float(), nullable=True),
    sa.Column('conclusion', sa.String(length=30), nullable=True),
    sa.Column('party_to_remit', sa.String(length=30), nullable=True),
    sa.Column('resolve_date', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['Order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Arbitration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Arbitration_id'), ['id'], unique=False)

    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arbitration_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('arbitration_ongoing', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('arbitration_conluded', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.drop_column('arbitration_conluded')
        batch_op.drop_column('arbitration_ongoing')
        batch_op.drop_column('arbitration_required')

    with op.batch_alter_table('Arbitration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Arbitration_id'))

    op.drop_table('Arbitration')
    # ### end Alembic commands ###
