"""added column to product_return

Revision ID: f6b6f1e4d6d0
Revises: c0951ef5ece2
Create Date: 2024-10-19 22:07:17.690773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b6f1e4d6d0'
down_revision = 'c0951ef5ece2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ProductReturn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_product_sent_out', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ProductReturn', schema=None) as batch_op:
        batch_op.drop_column('date_product_sent_out')

    # ### end Alembic commands ###
