"""added column to order - order conlcusion

Revision ID: faff9db1ed4c
Revises: 3151578f8f61
Create Date: 2024-10-12 19:03:24.576559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faff9db1ed4c'
down_revision = '3151578f8f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dispute_conclusion', sa.String(length=20)))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.drop_column('dispute_conclusion')

    # ### end Alembic commands ###
