"""added new columns relating to partial payment to order table

Revision ID: fc86e7f654fa
Revises: 31b11e97f186
Create Date: 2024-09-27 01:11:22.974630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc86e7f654fa'
down_revision = '31b11e97f186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partial_disbursements', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('partial_disbursement_approved', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('partial_disbursement_initiated', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('partial_disbursement_processing', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('partial_disbursement_dispatched', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.drop_column('partial_disbursement_dispatched')
        batch_op.drop_column('partial_disbursement_processing')
        batch_op.drop_column('partial_disbursement_initiated')
        batch_op.drop_column('partial_disbursement_approved')
        batch_op.drop_column('partial_disbursements')

    # ### end Alembic commands ###
